# /etc/amdfand/config.toml
log_level = "Error"
temp_input = "temp1_input"

[[speed_matrix]]
temp = 4.0
speed = 5.0

[[speed_matrix]]
temp = 20.0
speed = 10.0

[[speed_matrix]]
temp = 30.0
speed = 15.0

[[speed_matrix]]
temp = 35.0
speed = 15.0

[[speed_matrix]]
temp = 40.0
speed = 20.0

[[speed_matrix]]
temp = 50.0
speed = 25.0

[[speed_matrix]]
temp = 60.0
speed = 30.0

[[speed_matrix]]
temp = 60.0
speed = 40.0

[[speed_matrix]]
temp = 70.0
speed = 50.0

[[speed_matrix]]
temp = 80.0
speed = 70.0

[[speed_matrix]]
temp = 90.0
speed = 100.0
