[theme]
theme = "nord-dark"
[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
#max_width = 40
#show_marks = "visible"
[block.theme_overrides]
idle_bg = "#D8DEE9"
idle_fg = "#3B4252"

[[block]]
block = "net"
interval = 3
format = " $icon ↓:$graph_down ↑:$graph_up "
#on_click = "kitty -e nmtui"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
#device_format = "{icon}{name}{ap}"
#ap_format = "{ssid}"
[block.theme_overrides]
idle_bg = "#bf616a"
idle_fg = "#eceff4"

[[block]]
block = "temperature"
#collapsed = false
interval = 10
format = " CPU: $average "
chip = "k10temp-pci-00c3"
inputs = ["Tctl", "temp1_input"]
#on_click = "kitty -e gotop"
[block.theme_overrides]
idle_bg = "#a3be8c"
idle_fg = "#3b4252"
good_bg = "#88c0d0"
good_fg = "#3b4252"
warning_bg = "#d08770"
warning_fg = "#3b4252"
critical_bg = "#bf616a"
critical_fg = "#3b4252"

[[block]]
block = "temperature"
#collapsed = false
interval = 10
format = " GPU: $average "
chip = "amdgpu-pci-0900"
inputs = ["edge", "temp1_input"]
#on_click = "kitty -e nvtop"
[block.theme_overrides]
idle_bg = "#a3be8c"
idle_fg = "#3b4252"
good_bg = "#88c0d0"
good_fg = "#3b4252"
warning_bg = "#d08770"
warning_fg = "#3b4252"
critical_bg = "#bf616a"
critical_fg = "#3b4252"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available free "
[block.theme_overrides]
idle_bg = "#b48ead"
idle_fg = "#3b4252"

[[block]]
block = "memory"
format = " $icon $mem_used/$mem_total "
[block.theme_overrides]
idle_bg = "#d08770"
idle_fg = "#3b4252"

[[block]]
block = "sound"
#on_click = "kitty -e pulsemixer"
max_vol = 100

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%b %d, %H:%M') "
#on_click = "kitty -e calcurse"
[block.theme_overrides]
idle_bg = "#8FBCBB"
idle_fg = "#3B4252"
