[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#282c34"
idle_fg = "#61afef"
separator_bg = "#282c34"
separator_fg = "#abb2bf"

[icons]
icons = "awesome6"

[[block]]
block = "focused_window"
#max_width = 40
#show_marks = "visible"
[block.theme_overrides]

[[block]]
block = "toggle"
format = " $icon "
command_state = "pidof wlsunset"
command_on = "dinitctl start wlsunset"
command_off = "dinitctl stop wlsunset"
interval = 2
[block.icons_overrides]
toggle_on = "🌆"
toggle_off = "🏙️"


[[block]]
block = "net"
interval = 2
format = "$icon ↓:$speed_down ↑:$speed_up "
format_alt = "$device: $ipv6 $ip "
#on_click = "kitty -e nmtui"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
#device_format = "{icon}{name}{ap}"
#ap_format = "{ssid}"
[block.theme_overrides]

[[block]]
block = "temperature"
#collapsed = false
interval = 10
format = "CPU: $average"
chip = "k10temp-pci-00c3"
inputs = ["Tctl", "temp1_input"]
#on_click = "kitty -e gotop"
[block.theme_overrides]

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $available free"
[block.theme_overrides]

[[block]]
block = "memory"
format = "$icon$mem_used/$mem_total"
[block.theme_overrides]

[[block]]
block = "sound"
#on_click = "kitty -e pulsemixer"
max_vol = 100

[[block]]
block = "time"
interval = 60
format = "$icon $timestamp.datetime(f:'%b %d, %H:%M')"
#on_click = "kitty -e calcurse"
[block.theme_overrides]
