---
- name: Drop-in Directory
  ansible.builtin.file:
    state: directory
    path: "/etc/systemd/timesyncd.conf.d/"
    owner: root
    group: root
    mode: '0755'

- name: Configuration
  ansible.builtin.template:
    src: 'templates/10-timesyncd.conf.j2'
    dest: '/etc/systemd/timesyncd.conf.d/10-timesyncd.conf'
    owner: root
    group: root
    mode: '0644'

- name: Service
  ansible.builtin.systemd_service:
    name: 'systemd-timesyncd'
    enabled: true
