---
- name: Directory resolved.conf.d
  ansible.builtin.file:
    state: directory
    dest: "/etc/systemd/resolved.conf.d/"
    owner: root
    group: root
    mode: '0755'

- name: Configuration
  ansible.builtin.template:
    src: "templates/10-resolved.conf.j2"
    dest: "/etc/systemd/resolved.conf.d/10-resolved.conf"
    owner: root
    group: root
    mode: '0644'
  notify: Restart

- name: Stub resolv.conf
  ansible.builtin.file:
    state: link
    src: '/run/systemd/resolve/stub-resolv.conf'
    dest: '/etc/resolv.conf'
    force: true

- name: Service
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: started
    enabled: true
