---
- name: Arch Bootstrap
  hosts: localhost
  become: true

  pre_tasks:
    - name: Base Packages
      community.general.pacman:
        name: "{{ pacman_base_pkgs }}"
        state: present

  roles:
    - systemd-resolved
    - systemd-networkd
    - systemd-timesyncd

  tasks:
    - name: Enable SSD TRIM
      ansible.builtin.systemd_service:
        name: 'fstrim.timer'
        enabled: true
